### ISSUE TITLE
Title numbering in floating article content box of reviews is wrong

### ISSUE THREAD

**Issue by nielsdelporte** [archon810/androidpolice#2]
**What steps will reproduce the problem?**
1. Open a [review](http://www.androidpolice.com/2015/05/07/lg-watch-urbane-review-350-buys-you-the-nicest-android-wear-watch-yet-if-thats-something-you-want/)
2. Open article contents (red-pinkish box on the left)
3. Title numbering is not very logical

**What is the expected output? What do you see instead?**
I expected the titles of the review (design, quality, ...) to be either a subtitle of a "main content/review" title, or a ordinary title.
I see those titles as subtitles of "not so good" - which is not very logical from my point of view

**What operating system are you on?**
Windows 8.1 Pro (64-bit)

**What is your browser and its version?**
Google Chrome 42.0.2311.135 m (64-bit)
Mozilla Firefox 37.0.2

**Please provide any additional information below.**
I've found his in [this review](http://www.androidpolice.com/2015/04/27/alactel-onetouch-idol-3-5-5-review-250-buys-you-so-much-more-phone-than-it-used-to/) too (first one I found with an article contents box, had the same issue)
Here, the conclusion gets a single digit number, and is not a subtitle like in the first example. The other titles are still subtitles of "not so good" though.

**Comment by archon810** [comment]
Thanks, this was a test tracker, which we may or may not use in the future once Google Code does shut down. Right now, we're still using the Google Code tracker.
