### ISSUE TITLE
search doesnt work properly. Search by comment.

### ISSUE THREAD

**Issue by adenzil** [archon810/androidpolice#66]
I searched "marshmallow" and selected "comment" and this 3 year old article popped up with no reference to marshmallow.
<img width="1280" alt="screen shot 2015-08-20 at 2 03 11 pm" src="https://cloud.githubusercontent.com/assets/8273093/9379147/df77cb88-4744-11e5-84f4-6743016d5763.png">

**Comment by archon810** [comment]
Sure, it's there in the body.

"Yeah, you heard me, squishy plastic. You can easily flex it with a light touch, and you can feel the whole back deform in your hands when using it. It's sort of like holding a *marshmallow*. Don't believe me? Watch this:"
