### ISSUE TITLE
Waayyyyy too many requests on load

### ISSUE THREAD

**Issue by nickcoad** [archon810/androidpolice#67]
The Android Police front page loads 9.0 MB of data over the course of 276 requests and takes 11 seconds to load.  This can't be deliberate - did someone forget to concatenate and minify the CSS and JavaScript?

**Comment by nickcoad** [comment]
As an addendum, the number of requests drops to 140 with AdBlock enabled, meaning a MASSIVE 130 of those requests are coming from ads - wow! At any rate, the AdBlock-enabled total is still very high and probably deserves attention.

**Comment by archon810** [comment]
The front page contains things like videos, GIFs, and high quality images (we use PNGs for the most part). Also I noticed that if I disable browser caching (such as for a test like yours probably was), some things like GIFs and images, show up twice, which isn't a problem when caching is enabled.

But yeah, something crazy is going on with ad requests. They just keep going forever, and I hate every minute of it. God damn, I hate advertising networks. They just don't give a single fuck about performance and spew JS and tracking pixels everywhere.

I mean wtf:
![image](https://cloud.githubusercontent.com/assets/469543/9425505/bfd24f22-48c7-11e5-9205-875f42183a81.png)

**Comment by archon810** [comment]
Apparently it's a runaway script/ad network that's doing this, and we're going to track it down. A regular load without this phenomenon doesn't have nearly as many calls.

**Comment by archon810** [comment]
See https://plus.google.com/u/0/+ArtemRussakovskii/posts/VgrLdYcoifr.

I'm on a mission to eradicate any ads and ad networks that do shit like VPAID here. Fuck everything about this.

**Comment by archon810** [comment]
I'll close this ticket - it can never be "done", as it's really up to advertisers to change their ways, optimize code, etc.

**Comment by nickcoad** [comment]
I'd say as long as you did your best (which I believe you did) then you can consider it done :)
