### ISSUE TITLE
podcast post landing page in cms is using stale info for the irc embed

### ISSUE THREAD

**Issue by speakxj7** [archon810/androidpolice#68]
http://www.androidpolice.com/2015/05/22/the-android-police-podcast-live/

irc embed should be set to port 9090 and chat.andirc.net out of the box?

**Comment by archon810** [comment]
Sorry, I haven't paid attention to the IRC widget in a while but what's wrong with the current settings irc.andirc.net and 6667? I just tried it, and it worked OK.

**Comment by speakxj7** [comment]
Huh. It wasn't working here during last night's broadcast. Got a error in the widget, and a message about a stale link hitting it directly.

The contact page link for andirc still presents an error though. (And you should also embed the ap channel into that link)

**Comment by speakxj7** [comment]
yeah does seem to be working ok. must've gotten wires crossed with the contact page link.

**Comment by archon810** [comment]
Fixed contact page. Thanks!

**Comment by archon810** [comment]
I was getting a timeout now on the podcast page, so I updated the widget to use the correct chat.andirc.net and 9090 settings. We've also made it responsive so it no longer remains huge on mobile/tablet.

**Comment by speakxj7** [comment]
change the contact page link to preload with the ap channel?

chat.andirc.net:9090/?nick=&channels=androidpolice

**Comment by archon810** [comment]
I knew I forgot something! Fixed.
