### ISSUE TITLE
Android_Update_6.apk

### ISSUE THREAD

**Issue by erofich** [archon810/androidpolice#69]
When visiting mobile version from Russia, request for downloading Android_Update_6.apk appears.
Chrome latest stable version, Android 6.0.1.

**Comment by archon810** [comment]
This is a rogue ad in one of the ad networks that I've been trying to chase for a while. We're hoping to eradicate it and track down the network soon.

**Comment by Vanzent** [comment]
Привет. Вычислил банеры, которые прогружают этот apk. Куда писать, кому говорить?

**Comment by erofich** [comment]
Привет, да прямо здесь и пиши, Артём увидит, и примет необходимые действия.

**Comment by Vanzent** [comment]
Эти банеры вижу только в мобильном, перебрасывают на google play. В браузере их не видно, какой бы размер экрана и юзерагент ни ставил. Пока два банера видел. 
Какие еще данные нужны. Если только вид банера?
Первый ведет на "Galaxy Legend" издатель "tap4fun". Грузит apk c сайта http://slidetracking.ru/Android_Update_6.apk.
Второй ведет на "King's Empire" издатель тот же tap4fun. Узнать откуда грузит apk не успел.

**Comment by archon810** [comment]
I think it's safe to say Google AdSense or whoever was responsible for running these rogue ads has figured it out, or the attacks stopped, as I haven't heard of any resent reports of APKs getting automatically downloaded for a while now. I'm going to close this.

**Comment by anusakha** [comment]
Good
