### ISSUE TITLE
Toxic/malware ads on your site

### ISSUE THREAD

**Issue by mtmurdock** [archon810/androidpolice#72]
When I go to your website on my Android phone after a few seconds I am automatically navigated to a series of sites and am shown a bunch of messages like "YOU HAVE A VIRUS!!! CLICK TO FIX!!!". Sounds like you guys have let a malicious advertiser on the website.

**Comment by archon810** [comment]
This is something we're aware of, unfortunately, but there doesn't seem to be much we can do when someone targets our site through the most popular ad networks: https://plus.google.com/+ArtemRussakovskii/posts/28BtKzj7V34.

**Comment by archon810** [comment]
Looks like these stopped for the most part. I'm going to close this ticket.
