### ISSUE TITLE
comments not opening

### ISSUE THREAD

**Issue by jaylitten** [archon810/androidpolice#73]
#### Actual behavior
The comments section at the end of an article doesn't open in Firefox for Android. I have Ublock Origins installed. Stable version of Firefox on Android 7.

**Comment by archon810** [comment]
I just tried loading comments on a Nexus 6P running Android 7, but without Ublock Origins. The Disqus comments load fine. It's possible Ublock is blocking something it shouldn't, but adblock software-related issues are not supported, so I'm going to close this.
