### ISSUE TITLE
Great job guys!

### ISSUE THREAD

**Issue by moriel5** [archon810/androidpolice#75]
#### Expected behavior
Get to the Android Police bug tracker on Google Code.

#### Actual behavior
Google Code has shut down, so there is a link to GitHub.

#### Steps to reproduce the problem
1. Search for Android Police Files on Android Police.
2. Open Volume 11 of the Android Police Files.
3. Press the link to the Device Manager issue (😂) at the Android Police Bug Tracker.
4. Press the link to the GitHub page.

This was hilarious, keep it up guys!

Can this "issue" (without this line or my username) please be in the next installment of the Android Police Files?

**Comment by archon810** [comment]
Due to recursion, I must complete this ticket before the rift in the space time continuum.
